version: "3"

services:
  mariadb:
    image: mariadb:10.5.8
    hostname: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=MMd09EEDc
      - MYSQL_DATABASE=micromovie
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=MMd09EEDc
      - "MYSQL_ROOT_HOST=%"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    hostname: phpmyadmin
    ports:
      - 9999:80
    environment:
      - PMA_HOST=mariadb
      - UPLOAD_LIMIT=1G

  redis:
    container_name: redis
    restart: always
    image: redis
    ports:
      - 6379:6379
