basePath: /api/v1
definitions:
  apierrors.ApiError:
    type: object
  models.Movie:
    properties:
      director:
        type: string
      id:
        type: integer
      name:
        type: string
      stars:
        type: string
      writer:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Movies API service.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Movie API
  version: "1.0"
paths:
  /healthcheck:
    get:
      description: Health checking for the service
      operationId: HealthCheckController
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health Check
      tags:
      - monitoring
  /movies:
    get:
      consumes:
      - application/json
      description: get movies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Movie'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.ApiError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apierrors.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apierrors.ApiError'
      summary: List movies
      tags:
      - movies
    post:
      consumes:
      - application/json
      description: add by json movie
      parameters:
      - description: Add movie
        in: body
        name: movie
        required: true
        schema:
          $ref: '#/definitions/models.Movie'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Movie'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.ApiError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apierrors.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apierrors.ApiError'
      summary: Add a movie
      tags:
      - movies
  /movies/{id}:
    delete:
      consumes:
      - application/json
      description: Delete by movie id
      parameters:
      - description: movie id
        format: int64
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/models.Movie'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.ApiError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apierrors.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apierrors.ApiError'
      summary: Delete a movie
      tags:
      - movies
    get:
      consumes:
      - application/json
      description: get string by id
      parameters:
      - description: movie id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Movie'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.ApiError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apierrors.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apierrors.ApiError'
      summary: Show a movie
      tags:
      - movies
    patch:
      consumes:
      - application/json
      description: Update by json movie
      parameters:
      - description: movie id
        in: path
        name: id
        required: true
        type: integer
      - description: Update movie
        in: body
        name: movie
        required: true
        schema:
          $ref: '#/definitions/models.Movie'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Movie'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apierrors.ApiError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/apierrors.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apierrors.ApiError'
      summary: Update a movie
      tags:
      - movies
swagger: "2.0"
